In [ ]:
%tensorflow_version 2.x

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
path = '/content/data.txt'

In [ ]:
text = open(path, 'r').read()

In [ ]:
print(text[:300])

/ 




THE BOY WHO LIVED 

Mr. and Mrs. Dursley, of number four, Privet Drive, 
were proud to say that they were perfectly normal, 
thank you very much. They were the last people you’d 
expect to be involved in anything strange or 
mysterious, because they just didn’t hold with such 
nonsense. 

Mr.


In [ ]:
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '%', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '\\', ']', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '~', '—', '‘', '’', '“', '”', '•', '■']


90

In [ ]:
idx_to_char = np.array(vocab)

In [ ]:
idx_to_char[50]

'X'

In [ ]:
char_to_idx = {char:idx for idx,char in enumerate(vocab)}

In [ ]:
char_to_idx['a']

55

In [ ]:
encoded_text = np.array([char_to_idx[c] for c in text])

In [ ]:
encoded_text.shape

(3035402,)

In [ ]:
sample = text[:300]
sample

'/ \n\n\n\n\nTHE BOY WHO LIVED \n\nMr. and Mrs. Dursley, of number four, Privet Drive, \nwere proud to say that they were perfectly normal, \nthank you very much. They were the last people you’d \nexpect to be involved in anything strange or \nmysterious, because they just didn’t hold with such \nnonsense. \n\nMr.'

In [ ]:
encoded_text[:300]

array([12,  1,  0,  0,  0,  0,  0, 46, 34, 31,  1, 28, 41, 51,  1, 49, 34,
       41,  1, 38, 35, 48, 31, 30,  1,  0,  0, 39, 72, 11,  1, 55, 68, 58,
        1, 39, 72, 73, 11,  1, 30, 75, 72, 73, 66, 59, 79,  9,  1, 69, 60,
        1, 68, 75, 67, 56, 59, 72,  1, 60, 69, 75, 72,  9,  1, 42, 72, 63,
       76, 59, 74,  1, 30, 72, 63, 76, 59,  9,  1,  0, 77, 59, 72, 59,  1,
       70, 72, 69, 75, 58,  1, 74, 69,  1, 73, 55, 79,  1, 74, 62, 55, 74,
        1, 74, 62, 59, 79,  1, 77, 59, 72, 59,  1, 70, 59, 72, 60, 59, 57,
       74, 66, 79,  1, 68, 69, 72, 67, 55, 66,  9,  1,  0, 74, 62, 55, 68,
       65,  1, 79, 69, 75,  1, 76, 59, 72, 79,  1, 67, 75, 57, 62, 11,  1,
       46, 62, 59, 79,  1, 77, 59, 72, 59,  1, 74, 62, 59,  1, 66, 55, 73,
       74,  1, 70, 59, 69, 70, 66, 59,  1, 79, 69, 75, 85, 58,  1,  0, 59,
       78, 70, 59, 57, 74,  1, 74, 69,  1, 56, 59,  1, 63, 68, 76, 69, 66,
       76, 59, 58,  1, 63, 68,  1, 55, 68, 79, 74, 62, 63, 68, 61,  1, 73,
       74, 72, 55, 68, 61

In [ ]:
print(text[:200])

/ 




THE BOY WHO LIVED 

Mr. and Mrs. Dursley, of number four, Privet Drive, 
were proud to say that they were perfectly normal, 
thank you very much. They were the last people you’d 
expect to be i


In [ ]:
lines = '''
Mr. and Mrs. Dursley, of number four, Privet Drive, 
were proud to say that they were perfectly normal, 
thank you very much.
'''

In [ ]:
len(lines)

127

In [ ]:
seq_len = 120

In [ ]:
total_num_seq = len(text) // (seq_len+1)
total_num_seq

25085

In [ ]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [ ]:
for item in char_dataset.take(30):
  print(idx_to_char[item.numpy()])

/
 










T
H
E
 
B
O
Y
 
W
H
O
 
L
I
V
E
D
 




M
r
.


In [ ]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [ ]:
def seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [ ]:
dataset = sequences.map(seq_targets)

In [ ]:
for input_text, target_text in dataset.take(1):
  print(input_text.numpy())
  print(''.join(idx_to_char[input_text.numpy()]))
  print('\n')
  print(target_text.numpy())
  print(''.join(idx_to_char[target_text.numpy()]))

[12  1  0  0  0  0  0 46 34 31  1 28 41 51  1 49 34 41  1 38 35 48 31 30
  1  0  0 39 72 11  1 55 68 58  1 39 72 73 11  1 30 75 72 73 66 59 79  9
  1 69 60  1 68 75 67 56 59 72  1 60 69 75 72  9  1 42 72 63 76 59 74  1
 30 72 63 76 59  9  1  0 77 59 72 59  1 70 72 69 75 58  1 74 69  1 73 55
 79  1 74 62 55 74  1 74 62 59 79  1 77 59 72 59  1 70 59 72 60 59 57 74]
/ 




THE BOY WHO LIVED 

Mr. and Mrs. Dursley, of number four, Privet Drive, 
were proud to say that they were perfect


[ 1  0  0  0  0  0 46 34 31  1 28 41 51  1 49 34 41  1 38 35 48 31 30  1
  0  0 39 72 11  1 55 68 58  1 39 72 73 11  1 30 75 72 73 66 59 79  9  1
 69 60  1 68 75 67 56 59 72  1 60 69 75 72  9  1 42 72 63 76 59 74  1 30
 72 63 76 59  9  1  0 77 59 72 59  1 70 72 69 75 58  1 74 69  1 73 55 79
  1 74 62 55 74  1 74 62 59 79  1 77 59 72 59  1 70 59 72 60 59 57 74 66]
 




THE BOY WHO LIVED 

Mr. and Mrs. Dursley, of number four, Privet Drive, 
were proud to say that they were perfectl


In [ ]:
batch_size = 128
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder = True)

In [ ]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

In [ ]:
vocab_size = len(vocab)
embed_dims = 64
rnn_neurons = 1026


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Dropout, LSTM, GRU

In [ ]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [ ]:
def sparse_categorical_loss(y_true, y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits = True)

In [ ]:
def create_model(vocab_size, embed_dims, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dims,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_categorical_loss) 
    return model

In [ ]:
model = create_model(
  vocab_size = vocab_size,
  embed_dims=embed_dims,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [ ]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")


(128, 120, 90)  <=== (batch_size, sequence_length, vocab_size)


In [ ]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 90), dtype=float32, numpy=
array([[[-2.1172368e-03, -4.5779771e-03,  5.0322898e-04, ...,
          9.5545768e-04,  6.3933537e-04,  3.7225502e-04],
        [-1.0915010e-03, -1.4412240e-04,  6.3852202e-03, ...,
          1.2895546e-03,  2.7415282e-03, -9.6708734e-04],
        [ 2.8360088e-03, -3.4830242e-03,  9.0363137e-03, ...,
          1.3672671e-03,  3.5391052e-03, -6.1468035e-03],
        ...,
        [-3.2644861e-03, -4.4015129e-03,  5.2577681e-03, ...,
          7.3050633e-03,  1.1497852e-03, -6.2441346e-03],
        [-4.7364095e-03, -5.9509035e-03,  2.7815457e-03, ...,
          4.8519750e-03,  2.9720187e-03, -2.9612910e-03],
        [-3.3826481e-03, -1.4672871e-04,  6.0097489e-04, ...,
          8.1327762e-03,  4.1921493e-03, -3.2931687e-03]],

       [[-2.1172368e-03, -4.5779771e-03,  5.0322898e-04, ...,
          9.5545768e-04,  6.3933537e-04,  3.7225502e-04],
        [-3.5738200e-04, -7.2045540e-03, -6.7974273e-03, ...,
          7.9456717e-04, -3

In [ ]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [ ]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[48],
       [54],
       [83],
       [ 9],
       [ 4],
       [37],
       [ 3],
       [83],
       [25],
       [36],
       [ 1],
       [81],
       [40],
       [58],
       [58],
       [70],
       [87],
       [30],
       [67],
       [ 2],
       [85],
       [46],
       [30],
       [80],
       [45],
       [47],
       [26],
       [50],
       [44],
       [34],
       [20],
       [53],
       [36],
       [67],
       [87],
       [26],
       [ 5],
       [14],
       [21],
       [80],
       [42],
       [54],
       [64],
       [52],
       [46],
       [56],
       [31],
       [59],
       [31],
       [29],
       [78],
       [67],
       [58],
       [78],
       [46],
       [71],
       [69],
       [11],
       [60],
       [44],
       [83],
       [46],
       [15],
       [49],
       [87],
       [65],
       [55],
       [71],
       [56],
       [78],
       [82],
       [80],
       [50],
   

In [ ]:
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [ ]:
sampled_indices

array([48, 54, 83,  9,  4, 37,  3, 83, 25, 36,  1, 81, 40, 58, 58, 70, 87,
       30, 67,  2, 85, 46, 30, 80, 45, 47, 26, 50, 44, 34, 20, 53, 36, 67,
       87, 26,  5, 14, 21, 80, 42, 54, 64, 52, 46, 56, 31, 59, 31, 29, 78,
       67, 58, 78, 46, 71, 69, 11, 60, 44, 83, 46, 15, 49, 87, 65, 55, 71,
       56, 78, 82, 80, 50,  8, 10,  7, 11,  0, 78, 38, 49, 21, 82, 44, 49,
        0, 35, 88,  4, 47,  7, 75, 35, 83, 79, 74, 32, 61, 85, 34, 17, 13,
       36, 87, 59, 11, 80, 65, 23, 77, 57, 20, 28, 62, 47, 22, 36, 49, 33,
       79])

In [ ]:
print("Given the input seq: \n")
print("".join(idx_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(idx_to_char[sampled_indices ]))


Given the input seq: 

 feet. In his anger he seemed to fill 
the whole hut. The Dursleys were cowering against 
the wall. 

“Do you mean ter t


Next Char Predictions: 

V]—,%K"—>J |Nddp”Dm!’TDzSU?XRH7\Jm”?'18zP]jZTbEeECxmdxTqo.fR—T2W”kaqbx~zX*-).
xLW8~RW
I•%U)uI—ytFg’H40J”e.zk:wc7BhU9JWGy


In [ ]:
epochs = 30

In [ ]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
195/195 [==============================] - 19s 86ms/step - loss: 3.3547
Epoch 2/30
195/195 [==============================] - 18s 85ms/step - loss: 2.0630
Epoch 3/30
195/195 [==============================] - 18s 85ms/step - loss: 1.6587
Epoch 4/30
195/195 [==============================] - 18s 85ms/step - loss: 1.4341
Epoch 5/30
195/195 [==============================] - 18s 85ms/step - loss: 1.3093
Epoch 6/30
195/195 [==============================] - 18s 85ms/step - loss: 1.2329
Epoch 7/30
195/195 [==============================] - 18s 85ms/step - loss: 1.1775
Epoch 8/30
195/195 [==============================] - 18s 86ms/step - loss: 1.1362
Epoch 9/30
195/195 [==============================] - 18s 85ms/step - loss: 1.0992
Epoch 10/30
195/195 [==============================] - 18s 85ms/step - loss: 1.0668
Epoch 11/30
195/195 [==============================] - 18s 85ms/step - loss: 1.0398
Epoch 12/30
195/195 [==============================] - 18s 85ms/step - loss: 1.0117
E

In [ ]:
model.save('text_generation.h5') 

In [ ]:
from tensorflow.keras.models import load_model

In [ ]:
model = create_model(vocab_size, embed_dims, rnn_neurons, batch_size=1)

model.load_weights('text_generation.h5')

model.build(tf.TensorShape([1, None]))


In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (1, None, 64)             5760      
_________________________________________________________________
gru_1 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_1 (Dense)              (1, None, 90)             92430     
Total params: 3,459,366
Trainable params: 3,459,366
Non-trainable params: 0
_________________________________________________________________


In [ ]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
    num_generate = gen_size
    input_eval = [char_to_idx[s] for s in start_seed]
    input_eval = tf.expand_dims(input_eval, 0)
    text_generated = []
    temperature = temp
    model.reset_states()
    for i in range(num_generate):
      predictions = model(input_eval)
      predictions = tf.squeeze(predictions, 0)
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
      input_eval = tf.expand_dims([predicted_id], 0)
      text_generated.append(idx_to_char[predicted_id])
    return (start_seed + ''.join(text_generated))






In [ ]:
print(generate_text(model,"Yer a wizard Harry.",gen_size=2000))

Yer a wizard Harry. 

“You found it,” he snapped, still pink and fifty points from the fire, folded her hand utterly 
as Mr. Weasley were there, all of whom were 
clearly for what Hagrid meant you, exicy last year that you this too,” he said gently, people 
well my china. It was blind 
merely walking away back into King’s Cross 
with a huge mouth open front, Headmaster!” and already 
knocking it into Lockhart day. Fred and George had 
broken the Marauder’s Map wizards for funny 
they watched into the field. 

“They must not bl why seconds ... somebody get to 
Harry that Draco Malfoy would say he’d be daine, then.” 

Uncle Vernon set goarown on a shined 
you make you in the headmaster!” 

The hippogriff team was leaning away the mad his own wand 
at Harry, when Harry followed his nose against the jumpy 
clough he was worts ten familiar classigors and the schools, a 
changed pronounce he had over his head, which 
Harry stood hidden, because why he did?” 

While Malfoy rone off, as Harry’